/* confdefs.h */
#define PACKAGE_NAME "libsfork"
#define PACKAGE_TARNAME "libsfork"
#define PACKAGE_VERSION "0.0"
#define PACKAGE_STRING "libsfork 0.0"
#define PACKAGE_BUGREPORT "laurence.a.maddox@gmail.com"
#define PACKAGE_URL ""
#define PACKAGE "libsfork"
#define VERSION "0.0"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_STDLIB_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_GLITTER_H 1
#define HAVE_EZFORK_H 1
